# Generated by Django 4.2.7 on 2023-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_0007_autor_user_0008_livro_escritor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
