# Generated by Django 4.2.7 on 2023-11-30 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_autor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='escritor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.TextField(max_length=90),
        ),
    ]
