# Generated by Django 4.2.7 on 2023-11-30 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_livro_escritor_alter_livro_sinopse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
