# Generated by Django 4.2.7 on 2023-12-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_autor_data_nascimento_alter_autor_idade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'permissions': [('pode_publicar', 'Pode publicar um Livro')], 'verbose_name': 'Escritor', 'verbose_name_plural': 'Escritores'},
        ),
    ]
